AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAMLayerTest
  Sample SAM Template for SAMLayerTest

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  CurveFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: CurveFunction
      Description: Curve Function
      CodeUri: layer_curve/
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers: 
        - !Ref CommonLayer
        - !Sub arn:aws:lambda:us-east-1:408956450222:layer:lambda-layer-pandas:6
      Events:
        CurveAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /curve
            Method: post
  CashflowFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: CashflowFunction
      Description: Cashflow Function
      CodeUri: layer_cashflow/
      Handler: cashflowapp.cf_lambda_handler
      Runtime: python3.8
      Layers: 
        - !Ref CommonLayer
        - !Sub arn:aws:lambda:us-east-1:408956450222:layer:lambda-layer-pandas:6
      Events:
        CashflowAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /cashflow
            Method: post
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: sam-app-dependencies
      ContentUri: dependencies/
      CompatibleRuntimes:        
        - python3.8
        - python3.7
      RetentionPolicy: Retain
